name: Terraform AWS RDS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Check if Lambda exists
        id: check_lambda
        run: |
          if aws lambda get-function --function-name lambda-autenticacao --region us-east-1 > /dev/null 2>&1; then
            echo "lambda_exists=true" >> $GITHUB_OUTPUT
          else
            echo "lambda_exists=false" >> $GITHUB_OUTPUT
          fi   

      - name: Inicializar Terraform
        run: terraform init

      - name: Validar Terraform
        run: terraform validate

      - name: Import Lambda if it exists
        if: steps.check_lambda.outputs.lambda_exists == 'true'
        run: terraform import aws_lambda_function.lambda-autenticacao lambda-autenticacao

      - name: Planejar Terraform
        run: terraform plan
        env:
          TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}

      - name: Aplicar Terraform
        run: terraform apply -auto-approve
        env:
          TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}